version: '3'
services:
  shell:
    build: .
    image: eeweather_shell
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - .:/app

  test:
    image: eeweather_shell
    entrypoint: py.test -n0
    volumes:
      - .:/app
      - /app/tests/__pycache__/

  eeweather:
    image: eeweather_shell
    entrypoint: eeweather
    volumes:
      - .:/app

  python:
    image: eeweather_shell
    entrypoint: python
    volumes:
      - .:/app

  blacken:
    image: eeweather_shell
    entrypoint: black .
    volumes:
      - .:/app
