name: Publish to PyPi
on:
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/eeweather
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install build
        run: pip install build
      - name: Build distribution
        run: python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1